dist: xenial
sudo: false

branches:
  only:
    - master

language: ruby

addons:
  apt:
    packages:
      - graphviz

cache:
  - apt

before_install:
  - gem install asciidoctor pygments.rb
  - pip install Pygments

script:
  - make

after_success:
  - ./publish
