dist: bionic
sudo: false

branches:
  only:
    - master

language: ruby

addons:
  apt:
    packages:
      - graphviz

cache:
  - apt

before_install:
  - gem install asciidoctor pygments.rb
  - git clone -b 2.5.2 https://github.com/pygments/pygments.git

script:
  - pygmentize -V
  - make

after_success:
  - ./publish
