dist: xenial
sudo: false

branches:
  only:
    - master

language: ruby

addons:
  apt:
    packages:
      - graphviz

cache:
  - apt

before_install:
  - gem install asciidoctor coderay

script:
  - make

after_success:
  - ./publish
