dist: bionic
sudo: false

branches:
  only:
    - master

language: ruby

addons:
  apt:
    packages:
      - graphviz

cache:
  - apt

before_install:
  - gem install asciidoctor pygments.rb
  - git clone -b 2.5.2 https://github.com/pygments/pygments.git
  - git clone -b v2.1.0 --depth 1 https://github.com/lbovet/docson.git

script:
  - make

after_success:
  - ./publish
