dist: bionic
sudo: false

branches:
  only:
    - master

language: ruby

addons:
  apt:
    packages:
      - graphviz
      - python3-pygments

cache:
  - apt

before_install:
  - pygmentize -V
  - gem install asciidoctor pygments.rb
  - pygmentize -V

script:
  - make

after_success:
  - ./publish
